# Generated by Django 2.1.7 on 2022-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20221208_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dtm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
    ]
