# Generated by Django 4.0.3 on 2022-09-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_votor_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votor',
            new_name='voter',
        ),
    ]
